//訂單
export const PURCHASE_RESET = "PURCHASE_RESET";
export const GET_PURCHASE_REQUEST = "GET_PURCHASE_REQUEST";
export const GET_PURCHASE_SUCCESS = "GET_PURCHASE_SUCCESS";
export const GET_PURCHASE_FAILED = "GET_PURCHASE_FAILED";
//搜尋or分類篩選
export const NO_SEARCH = "NO_SEARCH";
export const GET_CARD = "GET_CARD";
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS";
export const GET_CARD_BYCATE = "GET_CARD_BYCATE";
//會員相關
export const GET_USER_COLLECTION_OK = "GET_USER_COLLECTION_OK";
export const GET_USER_COLLECTION_FAIL = "GET_USER_COLLECTION_FAIL";
//ETH
export const GET_ETH_SUCCESS = "GET_ETH_SUCCESS";
export const GET_ETH = "GET_ETH";
export const GET_TOP10_SUCCESS = "GET_TOP10_SUCCESS";